### PR TITLE
Clubhouse Project

### PR DESCRIPTION
**Pull request by SarvarKh**
# Clubhouse [Members Only!] project
### In this branch, I have:
- added post MVC functionality;
- added user MVC (with authentication);
- linked both models with each other;
- made the index page post authors only visible to sign in users

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @SarvarKh  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimum requirements of this project, keep it up, and your project is really almost done.
:+1: The following list of concerns are very commendable, keep up on implementing them in all your projects:
1. Your repository looks way professional,
2. Very good commit messages
3. You tried to make some styling for the project,

#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Instead of writing `LinkedIn`, `@twitterhandle`, `@githubhandle` for your social networks, replace those the link-texts with the usernames you use on those networks. For example: _Linkedin: [Sarvar Khalimov](https://www.linkedin.com/in/sarvar-khalimov/)_
- [ ] The `New post` button should not be shown on the navbar when a user is not logged in.
- [ ] The post creates the application routes using resources :posts, only: [:new, :create, :index] ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from Odin) 
- [ ] You have some logic in views: View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
  - [ ] There shoud be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright _=> To make sure that I clarify what you need to change on this reqirement: Ensure that there is no if conditions, and no loops in your view (`.html.erb`) files_

#### Resources to help you learn about this:

- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code/)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great job you've done so far on this project. I liked that you styled the app and you've completed most of the project requirements. However, and as described by the previous reviewer you still have few changes to make in order to make sure you've achieved mastery of this particular project.

- [x] Please use the correct RESTful resources on your routes
posts_routes_requirement

- [x] Kindly fix your sign-out feature. It's broken!
sign_in_out_link_requirement

<hr>

Kindly make those changes and you'll be good to go, also add to your readme the ```rails db:create``` CLI before the ```rails db:migrate``` one!

Good luck and happy coding 👨‍💻💻

**Comment by SarvarKh** [comment]
# Hi @MahmoudBakr23 thank you for your review. 
### Concerning your 1st comment:
I remember it was the project spec. However, I went ahead and added extra features like editing (f/e).
Acknowledging your request and considering it is a project requirement, I will implement it, but all other functions (like deleting) will not be available (at least).

### Concerning your 2nd comment:
I have rechecked it and it works smoothly, I can sign in, sign up, and sign out successfully (see the screenshot). 
Didn't you change anything in route or any other file before you clicked the sign-out button? 

I don't know exactly why it didn't work on your PC.

### Concerning your 3rd comment:
Thanks for detecting this missing step. I will implement it into a readme.

Screenshot from 2021-02-17 00-12-10
Screenshot from 2021-02-17 00-12-22

**Review by GzimAsani — APPROVED** [review]
# Status: APROVED  :tada: :tada: 
**Hello team** very good job, you can merge and continue in the next millstone

**I do not want to return you for only this reason so I will leave this as optional but highly recommended: ** 
- [ ] Add in your README file that the user needs to install yarn


_Don't forget to submit the completion form_

### HAPPY CODING :computer:

**Pull request merged**
